/*
 * This file is part of Princeps.
 *
 * Princeps is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Princeps is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Princeps.  If not, see <https://www.gnu.org/licenses/>.
 */

package princeps.process.builder.v3;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.BubbleColumnBlock;
import net.minecraft.world.level.block.LiquidBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.material.Fluids;

/**
 * Which cells are fluid, which bucket fills them, and — the half that matters more — which fluid cells no bucket can
 * ever fill.
 *
 * <p>Pure, so the rules below are testable rather than trusted. Every one of them is a vanilla fact that produces a
 * wrong build rather than an error when it is got wrong: a flowing water level cannot be placed, a bubble column is
 * not a block anybody places, and a waterlogged stair is a stair with a property and not a water cell at all.
 *
 * <h2>Why this is additive and cannot make anything worse</h2>
 *
 * <p>The bench excludes fluids from grading — {@code BenchSchematics.fromFile} drops every cell whose
 * {@code asItem()} is {@code Items.AIR}, which is all 602 water, 720 lava and 8 bubble-column cells of the owner's
 * basalt schematic. So no fluid cell is currently counted for or against any engine. A {@link BuildAction.FillFluid}
 * that works adds cells the old engine never built; one that does not fire changes nothing that was measured. The
 * only way this could HURT is by mistaking a non-fluid cell for a fluid one, which is why
 * {@link #sourceBucketFor} answers only for a genuine source block of a still fluid and {@code null} for every other
 * shape a fluid can take.
 */
public final class FluidPlan {

    private FluidPlan() {
    }

    /**
     * The bucket that places this state, or {@code null} when no bucket does.
     *
     * <p>Answers only for a SOURCE block of a still fluid — {@code water[level=0]} and {@code lava[level=0]}. Every
     * other fluid shape returns {@code null}, and each for its own reason:
     *
     * <ul>
     *   <li><b>A flowing level (1..15)</b> is a consequence, not a placement. It exists because a source exists
     *       somewhere uphill and it re-derives itself from the neighbourhood every tick; a bucket emptied into that
     *       cell produces a SOURCE, which is a different block from the one the schematic asked for and will flood
     *       what is below it. The honest answer is that the plan places the sources and lets the game produce the
     *       flow, and that any remaining mismatch is a named limitation.</li>
     *   <li><b>A bubble column</b> has no item at all. It is generated by soul sand or magma under water and its
     *       {@code drag} property follows from which of the two is beneath it, so the cell is built by building the
     *       block UNDER it and filling the water above — never by addressing the column.</li>
     *   <li><b>Waterlogging</b> is a property of another block, not a cell of its own. Filling it means clicking the
     *       already-placed stair or fence with a water bucket, which is a different action against a different
     *       target, and is deliberately out of scope: it is named in the plan report rather than half-done.</li>
     * </ul>
     */
    public static Item sourceBucketFor(BlockState desired) {
        if (desired == null || !(desired.getBlock() instanceof LiquidBlock)) {
            return null;
        }
        // LEVEL is 0 for a source and 1..15 for flowing. getFluidState().isSource() says the same thing and is the
        // form that survives a block whose LEVEL property is somehow absent.
        if (!desired.getFluidState().isSource()) {
            return null;
        }
        if (desired.getFluidState().is(Fluids.WATER)) {
            return Items.WATER_BUCKET;
        }
        if (desired.getFluidState().is(Fluids.LAVA)) {
            return Items.LAVA_BUCKET;
        }
        return null;
    }

    /** The bucket that turns the normally placed dry form of {@code desired} into its waterlogged form. */
    public static Item waterloggingBucketFor(BlockState desired) {
        return wantsWaterlogging(desired) ? Items.WATER_BUCKET : null;
    }

    /** Does the schematic ask for the waterlogged form of a block carrying the vanilla property? */
    public static boolean wantsWaterlogging(BlockState desired) {
        return desired != null
                && desired.hasProperty(BlockStateProperties.WATERLOGGED)
                && desired.getValue(BlockStateProperties.WATERLOGGED);
    }

    /** The filled bucket needed for either supported fluid operation. */
    public static Item bucketFor(BlockState desired) {
        Item source = sourceBucketFor(desired);
        return source != null ? source : waterloggingBucketFor(desired);
    }

    /** Is this a cell a bucket action can finish? */
    public static boolean isFillable(BlockState desired) {
        return bucketFor(desired) != null;
    }

    /**
     * State immediately after a water bucket is used on an already placed liquid container.
     *
     * <p>Only the WATERLOGGED bit changes. Returning {@code null} for every other input prevents the placement oracle
     * from accepting an arbitrary wrong base block merely because the desired state happens to be waterlogged.
     */
    public static BlockState waterloggedResult(BlockState placed, Item bucket) {
        if (placed == null || bucket != Items.WATER_BUCKET
                || !placed.hasProperty(BlockStateProperties.WATERLOGGED)
                || placed.getValue(BlockStateProperties.WATERLOGGED)) {
            return null;
        }
        return placed.setValue(BlockStateProperties.WATERLOGGED, true);
    }

    /**
     * Can one exact bucket use finish the placement result into the desired state?
     *
     * <p>The ordinary item-verify rules remain authoritative for every property except the bit the bucket changes.
     * A state that would still need a separate interaction is deliberately not accepted by this path: the bucket
     * acknowledgement carries one exact expected state, so it must be the cell's final state.
     */
    public static boolean canFinishWaterlogging(BlockState placed, BlockState desired, V3Settings settings) {
        if (!wantsWaterlogging(desired)) {
            return false;
        }
        BlockState wet = waterloggedResult(placed, Items.WATER_BUCKET);
        return wet != null && settings.valid(wet, desired, true);
    }

    /**
     * Cell affected by a bucket click, read from the LIVE state of the clicked block.
     *
     * <p>A dry liquid container consumes water in-place. An ordinary source fill lands on the far side of the
     * clicked face. This shared relationship is what prevents waterlogging from being modelled as a source in the
     * neighbouring cell.
     */
    public static BlockPos destination(BlockState liveClicked, BlockPos clicked, Direction face, Item bucket) {
        if (liveClicked == null || clicked == null || face == null || bucket == null) {
            return null;
        }
        if (waterloggedResult(liveClicked, bucket) != null) {
            return clicked;
        }
        if (bucket == Items.WATER_BUCKET || bucket == Items.LAVA_BUCKET) {
            return clicked.relative(face);
        }
        return null;
    }

    /** Is the immutable action schema internally consistent with its exact expected result? */
    public static boolean validTarget(BlockPos cell, BlockPos clicked, Direction face, Item bucket,
                                      BlockState expected) {
        if (cell == null || clicked == null || face == null || bucket == null || expected == null) {
            return false;
        }
        if (clicked.equals(cell)) {
            if (!wantsWaterlogging(expected) || bucket != Items.WATER_BUCKET) {
                return false;
            }
            BlockState dry = expected.setValue(BlockStateProperties.WATERLOGGED, false);
            return cell.equals(destination(dry, clicked, face, bucket))
                    && expected.equals(waterloggedResult(dry, bucket));
        }
        return clicked.relative(face).equals(cell) && sourceBucketFor(expected) == bucket;
    }

    /**
     * Is this a fluid cell the engine explicitly cannot build — the sentence the plan report owes the user up front?
     *
     * <p>Separate from "not fillable" because most cells are not fillable and are not fluid either. This one answers
     * only for the cells a human looking at the schematic would call water or lava and would reasonably expect to
     * appear.
     */
    public static boolean isUnbuildableFluid(BlockState desired) {
        if (desired == null) {
            return false;
        }
        if (desired.getBlock() instanceof BubbleColumnBlock) {
            return true;
        }
        if (desired.getBlock() instanceof LiquidBlock) {
            return !desired.getFluidState().isSource();
        }
        return false;
    }

    /**
     * Has the bucket landed? The confirmation {@link ActionRunner} holds for three ticks.
     *
     * <p>Compares the FLUID rather than the block state, because the state that appears is vanilla's own — the level,
     * and on some servers the falling flag — and an equality test against a hand-built expectation would refuse a
     * placement that is entirely correct.
     */
    public static boolean satisfies(BlockState live, BlockState expected) {
        return live != null && expected != null && live.equals(expected);
    }

    /**
     * What the slot holds after the bucket is emptied.
     *
     * <p>The material ledger needs it: a build with 602 water cells and one bucket is a build that walks back to a
     * water source 601 times, and that is a number worth knowing before the run rather than after it.
     */
    public static Item emptied(Item bucket) {
        return bucket == Items.WATER_BUCKET || bucket == Items.LAVA_BUCKET ? Items.BUCKET : bucket;
    }
}
